//
// Fetch errors
//
export enum WebcatErrorFetch {
  FETCH_PROMISE_MISSING = "ERR_WEBCAT_BUNDLE_FETCH_PROMISE_MISSING",
  FETCH_ERROR = "ERR_WEBCAT_BUNDLE_FETCH_ERROR",
}

//
// Bundle errors
//
export enum WebcatErrorBundle {
  ENROLLMENT_MISSING = "ERR_WEBCAT_BUNDLE_MISSING_ENROLLMENT",
  MANIFEST_MISSING = "ERR_WEBCAT_BUNDLE_MISSING_MANIFEST",
  SIGNATURES_MISSING = "ERR_WEBCAT_BUNDLE_MISSING_SIGNATURES",
}

//
// Enrollment errors
//
export enum WebcatErrorEnrollment {
  POLICY_MALFORMED = "ERR_WEBCAT_ENROLLMENT_POLICY_MALFORMED",
  POLICY_LENGTH = "ERR_WEBCAT_ENROLLMENT_POLICY_LENGTH",
  SIGNERS_MALFORMED = "ERR_WEBCAT_ENROLLMENT_SIGNERS_MALFORMED",
  SIGNERS_EMPTY = "ERR_WEBCAT_ENROLLMENT_SIGNERS_EMPTY",
  SIGNERS_KEY_MALFORMED = "ERR_WEBCAT_ENROLLMENT_SIGNERS_KEY_MALFORMED",
  THRESHOLD_MALFORMED = "ERR_WEBCAT_ENROLLMENT_THRESHOLD_MALFORMED",
  THRESHOLD_IMPOSSIBLE = "ERR_WEBCAT_ENROLLMENT_THRESHOLD_IMPOSSIBLE",
  MAX_AGE_MALFORMED = "ERR_WEBCAT_ENROLLMENT_MAX_AGE_MALFORMED",
  MISMATCH = "ERR_WEBCAT_ENROLLMENT_MISMATCH",
}

//
// Manifest errors
//
export enum WebcatErrorManifest {
  VERIFY_FAILED = "ERR_WEBCAT_MANIFEST_VERIFY_FAILED",
  THRESHOLD_UNSATISFIED = "ERR_WEBCAT_MANIFEST_THRESHOLD_UNSATISFIED",
  TIMESTAMP_MISSING = "ERR_WEBCAT_MANIFEST_MISSING_TIMESTAMP",
  TIMESTAMP_VERIFY_FAILED = "ERR_WEBCAT_MANIFEST_TIMESTAMP_VERIFY_FAILED",
  EXPIRED = "ERR_WEBCAT_MANIFEST_EXPIRED",
  FILES_MISSING = "ERR_WEBCAT_MANIFEST_FILES_MISSING",
  DEFAULT_INDEX_MISSING = "ERR_WEBCAT_MANIFEST_DEFAULT_INDEX_MISSING",
  DEFAULT_INDEX_MISSING_FILE = "ERR_WEBCAT_MANIFEST_DEFAULT_INDEX_MISSING_FILE",
  DEFAULT_FALLBACK_MISSING = "ERR_WEBCAT_MANIFEST_DEFAULT_FALLBACK_MISSING",
  DEFAULT_FALLBACK_MISSING_FILE = "ERR_WEBCAT_MANIFEST_DEFAULT_FALLBACK_MISSING_FILE",
  DEFAULT_CSP_MISSING = "ERR_WEBCAT_MANIFEST_DEFAULT_CSP_MISSING",
  DEFAULT_CSP_INVALID = "ERR_WEBCAT_MANIFEST_DEFAULT_CSP_INVALID",
  EXTRA_CSP_INVALID = "ERR_WEBCAT_MANIFEST_EXTRA_CSP_INVALID",
  EXTRA_CSP_MALFORMED = "ERR_WEBCAT_MANIFEST_EXTRA_CSP_MALFORMED",
  WASM_MISSING = "ERR_WEBCAT_MANIFEST_WASM_MISSING",
}

//
// CSP errors
//
export enum WebcatErrorCSP {
  PARSE_FAILED = "ERR_WEBCAT_CSP_PARSE_FAILED",
  MISMATCH = "ERR_WEBCAT_CSP_MISMATCH",
}

export enum WebcatErrorHeaders {
  MISSING = "ERR_WEBCAT_HEADERS_MISSING",
  LOCATION_EXTERNAL = "ERR_WEBCAT_HEADERS_LOCATION_EXTERNAL",
  FORBIDDEN = "ERR_WEBCAT_HEADERS_FORBIDDEN",
  DUPLICATE = "ERR_WEBCAT_HEADERS_DUPLICATE",
  MISSING_CRITICAL = "ERR_WEBCAT_HEADERS_MISSING_CRITICAL",
  ENROLLMENT_MALFORMED = "ERR_WEBCAT_HEADERS_ENROLLMENT_MALFORMED",
}

//
// Group wrapper (replacement for namespace WebcatErrorCode)
//
export const WebcatErrorCode = {
  Fetch: WebcatErrorFetch,
  Bundle: WebcatErrorBundle,
  Enrollment: WebcatErrorEnrollment,
  Manifest: WebcatErrorManifest,
  CSP: WebcatErrorCSP,
  Headers: WebcatErrorHeaders,
} as const;

//
// Union of all error enums
//
export type WebcatErrorCodeAny =
  | WebcatErrorFetch
  | WebcatErrorBundle
  | WebcatErrorEnrollment
  | WebcatErrorManifest
  | WebcatErrorCSP
  | WebcatErrorHeaders;

//
// Error object
//
export class WebcatError extends Error {
  constructor(
    public readonly code: WebcatErrorCodeAny,
    public readonly details?: string[],
  ) {
    super(code);
    this.name = "WebcatError";
  }
}
